// TinyHWDialect.cpp
#include "TinyHWDialect.h"
#include "TinyHWOps.td" // generated by TableGen
#include "mlir/IR/DialectImplementation.h"

using namespace mlir;
using namespace mlir::tinyhw;

TinyHWDialect::TinyHWDialect(MLIRContext *ctx)
    : Dialect("tinyhw", ctx, TypeID::get<TinyHWDialect>()) {
  addOperations<
#define GET_OP_LIST
#include "TinyHWOps.cpp.inc"
      >();
}
